version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - WEATHER_API_KEY=4efc17aba35df6203a76c60a83ef165a

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
